### ISSUE TITLE
商品搜索界面的多条件搜索有实现计划吗？

### ISSUE THREAD

**Issue by dxmeta** [GuoguoDad/jd_mall_flutter#1]
类似京东APP,商品搜索结果页面，多添加筛选有实现计划吗？比方价格排序，评价排序，销量排序，以及侧滑的更多筛选

**Comment by GuoguoDad** [comment]
> 类似京东APP,商品搜索结果页面，多添加筛选有实现计划吗？比方价格排序，评价排序，销量排序，以及侧滑的更多筛选

这个布局没什么难点啊，Scaffold嵌套CustomScrollView就可以实现，比首页容易多了
