### ISSUE TITLE
执行npm i 安装依赖报错，

### ISSUE THREAD

**Issue by wangxingsheng** [GuoguoDad/jd_mall_flutter#2]
![image](https://github.com/GuoguoDad/jd_mall_flutter/assets/39944221/0658d804-e09a-4f48-a2b1-e4679343f7ae)

**Comment by GuoguoDad** [comment]
用淘宝源，搜下npm切淘宝源，或者跑prd用线上服务



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 汪兴胜 ***@***.***&gt;
发送时间: 2023年8月31日 15:15
收件人: GuoguoDad/jd_mall_flutter ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [GuoguoDad/jd_mall_flutter] 执行npm i 安装依赖报错， (Issue #2)
