### ISSUE TITLE
Android studio编译运行在iPhone模拟器上图片全部加载失败

### ISSUE THREAD

**Issue by williamxiaolong** [GuoguoDad/jd_mall_flutter#3]
为何我用Android studio编译运行在iPhone模拟器上图片全部加载失败，然后停止运行项目，点击app打开图片全部就显示正常，一直没找到这个问题怎么解决。
<img width="959" alt="image" src="https://github.com/GuoguoDad/jd_mall_flutter/assets/12405241/cba927ac-10f9-4c55-9071-6eb6ee19bc71">

**Comment by GuoguoDad** [comment]
你的flutter什么版本的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: williamxiaolong ***@***.***&gt;
发送时间: 2023年11月3日 17:13
收件人: GuoguoDad/jd_mall_flutter ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3)

**Comment by williamxiaolong** [comment]
flutter版本是 3.13.0

**Comment by williamxiaolong** [comment]
> 你的flutter什么版本的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: williamxiaolong ***@***.***&gt; 发送时间: 2023年11月3日 17:13 收件人: GuoguoDad/jd_mall_flutter ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3)

flutter版本是 3.13.0

**Comment by GuoguoDad** [comment]
> > 你的flutter什么版本的 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: williamxiaolong _**@**_._**> 发送时间: 2023年11月3日 17:13 收件人: GuoguoDad/jd_mall_flutter _**@**_.**_> 抄送: Subscribed _**@**_.***> 主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3)
> 
> flutter版本是 3.13.0

猜测是环境问题，检查模拟器是否正常上网，网络是否正常，图片链接在浏览器中打开是否正常

**Comment by williamxiaolong** [comment]
> > > 你的flutter什么版本的 发自我的iPhone
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: williamxiaolong _**@**_._**> 发送时间: 2023年11月3日 17:13 收件人: GuoguoDad/jd_mall_flutter _**@**_.**_> 抄送: Subscribed _**@**_.***> 主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3)
> > 
> > 
> > flutter版本是 3.13.0
> 
> 猜测是环境问题，检查模拟器是否正常上网，网络是否正常，图片链接在浏览器中打开是否正常

网络正常的，通过Android studio编译运行在iPhone模拟器上图片全部加载失败，接下来停止运行，然后再点击app打开就一切正常了

**Comment by GuoguoDad** [comment]
3.13.7



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: williamxiaolong ***@***.***&gt;
发送时间: 2023年11月8日 11:14
收件人: GuoguoDad/jd_mall_flutter ***@***.***&gt;
抄送: LiuHui ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3)





    
你的flutter什么版本的 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: williamxiaolong @.&gt; 发送时间: 2023年11月3日 17:13 收件人: GuoguoDad/jd_mall_flutter _@**._&gt; 抄送: Subscribed _@_.*&gt; 主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3)
  
flutter版本是 3.13.0
  
猜测是环境问题，检查模拟器是否正常上网，网络是否正常，图片链接在浏览器中打开是否正常
  
网络正常的，通过Android studio编译运行在iPhone模拟器上图片全部加载失败，接下来停止运行，然后再点击app打开就一切正常了

**Comment by williamxiaolong** [comment]
> 3.13.7 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: williamxiaolong ***@***.***&gt; 发送时间: 2023年11月8日 11:14 收件人: GuoguoDad/jd_mall_flutter ***@***.***&gt; 抄送: LiuHui ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3) 你的flutter什么版本的 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: williamxiaolong @.&gt; 发送时间: 2023年11月3日 17:13 收件人: GuoguoDad/jd_mall_flutter _@**._&gt; 抄送: Subscribed _@_.*&gt; 主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3) flutter版本是 3.13.0 猜测是环境问题，检查模拟器是否正常上网，网络是否正常，图片链接在浏览器中打开是否正常 网络正常的，通过Android studio编译运行在iPhone模拟器上图片全部加载失败，接下来停止运行，然后再点击app打开就一切正常了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

<img width="318" alt="image" src="https://github.com/GuoguoDad/jd_mall_flutter/assets/12405241/f5c09944-0601-4add-bb97-355702c6daf2">
这样的，就连项目本地的图片都出不来，现在用的 3.13.7 flutter版本还是这样哦

**Comment by GuoguoDad** [comment]
> > 3.13.7 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: williamxiaolong _**@**_._**> 发送时间: 2023年11月8日 11:14 收件人: GuoguoDad/jd_mall_flutter _**@**_.**_> 抄送: LiuHui _**@**_._**>, Comment _**@**_.**_> 主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3) 你的flutter什么版本的 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: williamxiaolong @.> 发送时间: 2023年11月3日 17:13 收件人: GuoguoDad/jd_mall_flutter _@**._> 抄送: Subscribed _@_._> 主题: Re: [GuoguoDad/jd_mall_flutter] Android studio编译运行在iPhone模拟器上图片全部加载失败 (Issue #3) flutter版本是 3.13.0 猜测是环境问题，检查模拟器是否正常上网，网络是否正常，图片链接在浏览器中打开是否正常 网络正常的，通过Android studio编译运行在iPhone模拟器上图片全部加载失败，接下来停止运行，然后再点击app打开就一切正常了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_._**>
> 
> <img alt="image" width="318" src="https://user-images.githubusercontent.com/12405241/281252547-f5c09944-0601-4add-bb97-355702c6daf2.png"> 这样的，就连项目本地的图片都出不来，现在用的 3.13.7 flutter版本还是这样哦

试试 flutter run --no-enable-impeller
